### ISSUE TITLE
Newsletter, sauvegarde automatique sur les brouillons

### ISSUE THREAD

**Issue by thibaudgg** [acp-admin/acp-admin#109]
Sauvegarder automatiquement tout les X secondes les brouillons des newsletters lorsqu'elles sont modifiées pour éviter les pertes d'information.

Essayer avec:
https://www.stimulus-components.com/docs/stimulus-rails-autosave/

**Comment by secretariatldc** [comment]
merci :-)

**Comment by thibaudgg** [comment]
Voilà, le formulaire des brouillons des newsletters est maintenant sauvegardé sur le navigateur (en local), exemple quand la page est re-ouverte sans que le bouton de sauvegarde n'ai été pressé.

![Image](https://github.com/acp-admin/acp-admin/assets/1322/ef675698-7a5a-4ccb-b839-186eecd380f4)
