### ISSUE TITLE
Inscription, choix de facturation sous forme de liste déroulante

### ISSUE THREAD

**Issue by thibaudgg** [acp-admin/acp-admin#47]
Afficher les choix de facturation (voir image ci-dessous) sous la forme d'une liste déroulante (avec toujours "Annuelle" par défaut) plutôt que des boutons radio. Cela permettrait de gagner un peu de place.

![Image](https://user-images.githubusercontent.com/1322/170685076-51b2a293-80e8-462a-bf8a-21c74b873aef.png)

Questions:
- Est-ce que cela devrait être paramétrable (je dirais que non)?

**Comment by secretariatldc** [comment]
il faudrait une unité graphique je pense, si les dépôts sont en liste, ce paramètre aussi devrait l'être

**Comment by DavidGoupil** [comment]
Je ne pense pas qu'il soit nécessaire que ce soit paramétrable

**Comment by thibaudgg** [comment]
Je vais fermer cette amélioration, cela me semble plus clair d'avoir directement toutes les options visibles en un coup d'oeil plutôt que de passer par un menu déroulant.
