### ISSUE TITLE
Inscription, choix du dépôt sous forme de liste déroulante

### ISSUE THREAD

**Issue by thibaudgg** [acp-admin/acp-admin#48]
Les ACP avec un grand nombre de dépôts se retrouve rapidement avec un formulaire assez long, l'idée serait donc de proposer la liste des dépôts sous une forme plus compacte via une liste déroulante.

Questions:
Est-ce qu'il faudrait aussi une liste déroulante (à choix multiple) pour le choix de dépôt(s) alternatif(s)? 
Est-ce que l'affichage sous forme de boutons radio ou liste déroulante devrait être paramétrable ou alors automatique (par exemple dès que plus que X dépôts)?

Similaire à https://github.com/acp-admin/acp-admin/issues/47
Liée à https://github.com/acp-admin/acp-admin/issues/46

**Comment by secretariatldc** [comment]
Est-ce qu'il faudrait aussi une liste déroulante (à choix multiple) pour le choix de dépôt(s) alternatif(s)? Si le dépôt principal est en liste alors oui le dépôt alternatif doit l'être aussi.

**Comment by LunaSartori** [comment]
Est-ce possible de faire disparaitre certains dépots dans la liste déroulante lorsqu'ils sont pleins?

**Comment by thibaudgg** [comment]
> Est-ce possible de faire disparaitre certains dépots dans la liste déroulante lorsqu'ils sont pleins?

Oui, il déjà possible de rendre un dépôt non-visible en le modifiant.

**Comment by thibaudgg** [comment]
Je vais fermer cette amélioration, cela me semble plus clair d'avoir directement toutes les options visibles en un coup d'oeil plutôt que de passer par un menu déroulant. Avec le nombre d'information affiché par dépôt c'est également complexe à implémenter.
