### ISSUE TITLE
Inscription/renouvellement, choix du nombre de participations aux activités (demi-journées)

### ISSUE THREAD

**Issue by thibaudgg** [acp-admin/acp-admin#49]
La possibilité d'augmenter ou réduire le nombre de participations aux activités par abonnement est déjà possible via la partie administrative, mais ne l'est pas lors de l'inscription.

L'idée serait que chaque ACP puisse choisir (ou non) de rendre possible la sélection d'un nombre de participations différent  (min et max) de celui définit par la taille de panier choisi, soit en plus (par exemple 2 à 8) ou en moins (par exemple 0 à 4).

Le prix de l'abonnement serait alors automatiquement ajusté en fonction du prix de la participation (définis dans les paramètres) et de la différence du nombre de participations défini par défaut pour la taille de panier.

Questions:
- Est-ce qu'un texte d'explication supplémentaire paramétrable serait-il utile?

**Comment by DavidGoupil** [comment]
Ne nous concerne pas pour le moment...

**Comment by secretariatldc** [comment]
nous non plus

**Comment by MulePrilly** [comment]
cela nous serez utile - LaMule
