### ISSUE TITLE
Contenu paniers: modification manuelle des % de distribution

### ISSUE THREAD

**Issue by thibaudgg** [acp-admin/acp-admin#52]

**Comment by DavidGoupil** [comment]
Oui:)

**Comment by thibaudgg** [comment]
@DavidGoupil j'ai prévu de faire ça cette semaine. :)

**Comment by thibaudgg** [comment]
Voilà, il est maintenant possible d'éditer les % à la main 🎉  

![Image](https://user-images.githubusercontent.com/1322/205358630-0a013558-795f-46e3-8296-4ca198e85a6b.png)

**Comment by thibaudgg** [comment]
Temps: ~3h
