### ISSUE TITLE
Contenu paniers: arrondi au 1gr plutôt que 10gr

### ISSUE THREAD

**Issue by thibaudgg** [acp-admin/acp-admin#53]

**Comment by DavidGoupil** [comment]
On en a déjà parlé. Ce serait super pour les petites quantités.

**Comment by thibaudgg** [comment]
Je m'occupe de ça cette semaine aussi.

**Comment by thibaudgg** [comment]
C'est fait!

<img width="968" alt="image" src="https://user-images.githubusercontent.com/1322/205332048-a0d638c4-0e8c-4fe6-adf8-18f857b9e244.png">

**Comment by thibaudgg** [comment]
Temps: ~1h
