### ISSUE TITLE
Newsletter / emails groupés

### ISSUE THREAD

**Issue by thibaudgg** [acp-admin/acp-admin#54]
Ajouter un mini-mailchimp interne, avec les fonctionnalités suivantes:

- [x] Gestion de templates, avec bloc de contenu editable. (temps: 16h, https://github.com/acp-admin/acp-admin/commit/bd9fd9b73acbf8e49d2be43bf2aed5a7356bd076)
- [x] Choix des membres destinataires (par status, tailles de dépôt, dépôt, participations manquantes, ...) (temps: 4h, https://github.com/acp-admin/acp-admin/commit/5f3f8c0cdf79b531235fcea1f5383d14063c9847)
- [x] Gestion des inscrits, page de désinscription, synchronisation des désinscriptions avec Mailchimp
- [x] Gestion des envois et sauvegarde du status/contenu pour chaque membre concerné
- [x] Templates par défaut (text simple, prochain panier, contenu panier, activité, ... https://github.com/acp-admin/acp-admin/commit/ff3756ca376b49092c68c7cbca87f0125a891089)
- [x] Possibilité de dupliquer/copier facilement un template ou une newsletter existante (https://github.com/acp-admin/acp-admin/commit/ad1659878a0b239aad2a0fcb9a327b9920b9fe64)
- [ ] Documentation

**Comment by secretariatldc** [comment]
C'est vrai que Mailchimp est parfois un peu compliqué mais il offre pas mal de choix afin de choisir les destinataires, mettras-tu autant de paramètres à disposition? En plus en tout cas pour nous c'est gratuit donc je ne sais pas sûr que cela soit pertinent de réinventer la roue si cela demande beaucoup de boulot...
Après si certaines ACP peuvent insérer les contenus qu'ils créent dans ACP-admin en automatique dedans je vois le + pour celles-ci?
Peut-être serait-ce aussi moins lourd au niveau système qui n'aurait pas besoin de faire une mise à jour vers mailchimp chaque nuit?

**Comment by thibaudgg** [comment]
La synchronisation prends surtout du temps à mettre en place, il faut aussi copier/éditer le template sur mailchimp, expliquer comment les segments marche... et il y'a des fois couac avec des emails invalides. 

L'idée n'est pas de ré-inventer complètement mailchimp, mais fournir les fonctionnalités les plus pertinentes. Le choix des membres ciblés (par dépôts, statuts, taille de paniers, ...) est certainement quelques choses qui devrait être dispo. La possibilité pour les membres de s'inscrire/désinscrire depuis leur page de membre serait aussi un grand plus.

La fonctionnalité pourrait également évoluer en fonction des besoins, j'essayerai d'aller au plus simple au début.
