### ISSUE TITLE
Épicerie: Livraisons spéciales

### ISSUE THREAD

**Issue by thibaudgg** [acp-admin/acp-admin#55]
Permettre de gérer et de migrer la fonction des achats groupés dans l'épicerie. L'idée à terme est de supprimer les achats groupés.

Ajout de "livraisons spéciales" dans l'épicerie en addition des livraisons de paniers.

Besoins:
- Date
- Date de commande limite
- Date d’apparence 
- Texte spécial
- Liste de produit visible spécifique

Script de migration pour des producteurs/produits d'achats groupés à l'épicerie.

**Comment by secretariatldc** [comment]
Il faudrait aussi que l'on puisse sortir le détail des commandes par fournisseur et le total des commandes par fournisseur
