### ISSUE TITLE
Membre: changement du dépôt par livraison

### ISSUE THREAD

**Issue by thibaudgg** [acp-admin/acp-admin#56]
Ajout d'une option (désactivée par défaut) permettant aux membres de pouvoir changer le lieu de dépôt pour les livraisons futures depuis leur page de membre.

- Texte spéciale possible?
- Seulement dépôt visible (+ dépôt existant de l'abonnement)
- Facture changé comme si un admin faisait la modification.

**Comment by secretariatldc** [comment]
Est-ce qu'il serait possible dans ce cas de bloquer certain dépôt surchargé?

**Comment by thibaudgg** [comment]
On pourrait imaginer une option "permettre la modification depuis la page de membre" par dépôt qui serait activée par défaut. Mais les dépôts non-visible ne serait de toute façon pas proposé.

**Comment by thibaudgg** [comment]
@secretariatldc pour le moment tous les dépôts sont accessible, la modification étant déjà assez conséquente, on pourra toujours affiner les réglages dans le future si besoin.

Temps: ~8h
