### ISSUE TITLE
Newletter, choix de signature

### ISSUE THREAD

**Issue by secretariatldc** [acp-admin/acp-admin#79]
Faire que la signature par défaut ainsi que l'adresse mail d'envoi puisse être modifiable au cas où d'autres personnes utilisent les envois de mails acp-admin

**Comment by thibaudgg** [comment]
Il est maintenant possible de changer l'adresse d'envoi et la signature par défaut d'une newsletter.

https://github.com/acp-admin/acp-admin/commit/4ba98da7f7fe3d8709c95e5093c0f8515dbeb79b

**Comment by thibaudgg** [comment]
Temps: ~1h30
