### ISSUE TITLE
Newsletter, développement de l'audience

### ISSUE THREAD

**Issue by secretariatldc** [acp-admin/acp-admin#80]
Permettre de définir plus en détail l'audience, par exemple en permettant la sélection de :
une date de livraison future spécifique (très utile lors des changements de saison) 
une date de mise en panier
plusieurs dépôts
un abonnement spécifique avec un dépôt en cas d'envoi d'informations distinctes
un petit lien avec l'épicerie et la facturation?

**Comment by thibaudgg** [comment]
J'ai ajouté les segments d'audience suivants:
- [Livraison](https://github.com/acp-admin/acp-admin/commit/aca2c5e6caa82874e298e627d5ec3e319945991d) (8 prochaines, celle(s) de la semaine précédente incluse(s))
- [Activité](https://github.com/acp-admin/acp-admin/commit/a3aeedb72bcbe7b71ca5affcd6072b3b808bf861) (12 prochaines dates avec des participants)
- [Commandes épicerie](https://github.com/acp-admin/acp-admin/commit/b91fa33b2257a924c63e082144db2adc7cb7a767) (8 prochaines, celle(s) de la semaine précédente incluse(s))
- [Factures ouvertes](https://github.com/acp-admin/acp-admin/commit/8d227f98e7e3f6b11c1ddaedf276580930a00009) (toutes ou seulement avec rappel(s))

> plusieurs dépôts

Cela est difficile à mettre en place, avec la possibilité de facilement dupliquer une newsletter existante, je ne suis pas sûr que cela soit nécessaire pour le moment même si ce n'est pas idéal quand on veut s'adresser à la moitié des dépôts. 😅

> un abonnement spécifique avec un dépôt en cas d'envoi d'informations distinctes

La combinaison de plusieurs critères est assez difficile à mettre en place. À re-discuter si vraiment nécessaire.

**Comment by thibaudgg** [comment]
Temps: ~3h
