### ISSUE TITLE
Newsletter, audiences avancées

### ISSUE THREAD

**Issue by thibaudgg** [acp-admin/acp-admin#81]
Idées/demandes:

- Plutôt qu'une seule audience, pouvoir choisir plusieurs audiences soit du même type (2 dépôts en même) soit de type différents (dépôt et taille de panier).
- Date/année fiscale du premier abonnement (nouveaux vs anciens abonnés)

**Comment by thibaudgg** [comment]
@DavidGoupil tu peux maintenant cibler les premiers abonnements avec l'option suivante:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/1322/231108632-eae8464e-6945-476e-a798-09320a1ae505.png">

**Comment by DavidGoupil** [comment]
Top!! Merci pour la qualité de ce développement
