### ISSUE TITLE
Fiche de livraison (PDF)

### ISSUE THREAD

**Issue by thibaudgg** [acp-admin/acp-admin#82]
Certaines ACP utilise les dépôts pour regrouper les membres qui sont livrés à domicile par différent moyen (vélo, voiture tourné #1, voiture tourné #2, ...). Dans ce cas de figure, la fiche signature (PDF) n'est pas très utile et il lui manque certaine information (adresse, code du bâtiment, ...).

L'idée serait d'ajouter un "mode fiche (PDF)" au dépôt (signature ou livraison) afin de changer le rendu du PDF en fonction des besoins.

**Comment by LunaSartori** [comment]
Pour TaPatate nous aurions besoin d'une synthèse sur une page. Comme une image vaut 1000 mots voilà un exemple! :


![Image](https://user-images.githubusercontent.com/130671862/231988273-47fcca9d-5166-4186-8a82-b1bc0581b7ee.jpg)

En complément et si possible une résumé par dépot serait aussi super 


![Image](https://user-images.githubusercontent.com/130671862/231988738-3fd9dbef-4084-4c7c-9edf-1f3bb9b68c08.jpg)



![Image](https://user-images.githubusercontent.com/130671862/231988752-9d21b649-7722-4863-ab01-d3cfc9096852.jpg)

**Comment by thibaudgg** [comment]
Voilà un aperçu de l'affichage en mode "livraison à domicile":


![Image](https://github.com/acp-admin/acp-admin/assets/1322/292c98db-d906-41d0-a3ee-be182f2821eb)

Temps: ~7h
