### ISSUE TITLE
Compte membre, permettre de modifier les compléments panier

### ISSUE THREAD

**Issue by PatriciaCocagne** [acp-admin/acp-admin#85]
Sur le compte utilisateur, sur la page des livraisons, ajouter une option (/settings#membership) pour permettre au membre de modifier les compléments de panier. Identique à la logique qui permet la modification du dépôt mais uniquement au niveau des livraisons.

- Possibilité d'ajouter, enlever, ou modifier la quantité de chaque complément.

**Comment by thibaudgg** [comment]
Temps: ~2h30
